-- SkillBridge — Kategoriler, beceriler ve kullanıcı-beceri ilişkileri

CREATE TABLE public.categories (
  category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  icon TEXT,
  color TEXT DEFAULT '#6C5CE7',
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

CREATE TABLE public.skills (
  skill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_name TEXT NOT NULL UNIQUE,
  category_id BIGINT REFERENCES public.categories (category_id) ON DELETE SET NULL,
  category_name TEXT NOT NULL,
  type public.skill_type NOT NULL DEFAULT 'technical',
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX idx_skills_category_id ON public.skills (category_id);
CREATE INDEX idx_skills_category_name ON public.skills (category_name);

-- Kullanıcının sahip olduğu / öğretmek istediği beceriler
CREATE TABLE public.user_skills (
  user_id UUID NOT NULL REFERENCES public.profiles (user_id) ON DELETE CASCADE,
  skill_id BIGINT NOT NULL REFERENCES public.skills (skill_id) ON DELETE CASCADE,
  proficiency_level INTEGER NOT NULL DEFAULT 3 CHECK (proficiency_level BETWEEN 1 AND 5),
  can_teach BOOLEAN NOT NULL DEFAULT false,
  wants_to_learn BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  PRIMARY KEY (user_id, skill_id)
);

CREATE INDEX idx_user_skills_can_teach ON public.user_skills (user_id) WHERE can_teach = true;
CREATE INDEX idx_user_skills_wants_to_learn ON public.user_skills (user_id) WHERE wants_to_learn = true;

-- Kullanıcının mentorluk verdiği kategoriler
CREATE TABLE public.user_categories (
  user_id UUID NOT NULL REFERENCES public.profiles (user_id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES public.categories (category_id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  PRIMARY KEY (user_id, category_id)
);
