-- SkillBridge — Sertifikalar, rozetler ve bildirimler

CREATE TABLE public.certificates (
  certificate_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles (user_id) ON DELETE CASCADE,
  issuer_id UUID NOT NULL REFERENCES public.profiles (user_id) ON DELETE RESTRICT,
  session_id UUID REFERENCES public.sessions (session_id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  category_name TEXT NOT NULL,
  score INTEGER CHECK (score BETWEEN 0 AND 100),
  credential_id TEXT NOT NULL UNIQUE,
  skills TEXT[] NOT NULL DEFAULT '{}',
  color TEXT DEFAULT '#6C5CE7',
  issued_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX idx_certificates_user ON public.certificates (user_id, issued_at DESC);

CREATE TABLE public.badges (
  badge_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  icon TEXT NOT NULL,
  description TEXT NOT NULL,
  criteria JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE public.user_badges (
  user_id UUID NOT NULL REFERENCES public.profiles (user_id) ON DELETE CASCADE,
  badge_id BIGINT NOT NULL REFERENCES public.badges (badge_id) ON DELETE CASCADE,
  earned_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  PRIMARY KEY (user_id, badge_id)
);

CREATE TABLE public.notifications (
  notification_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles (user_id) ON DELETE CASCADE,
  type public.notification_type NOT NULL DEFAULT 'system',
  title TEXT,
  body TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}',
  is_read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX idx_notifications_user ON public.notifications (user_id, created_at DESC);
CREATE INDEX idx_notifications_unread ON public.notifications (user_id) WHERE is_read = false;

-- Quiz soruları (AI Chat Quiz modülü için temel yapı)
CREATE TABLE public.quiz_questions (
  question_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lesson_id UUID REFERENCES public.lessons (lesson_id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  options JSONB NOT NULL,
  correct_index INTEGER NOT NULL CHECK (correct_index >= 0),
  explanation TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

CREATE TABLE public.quiz_attempts (
  attempt_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles (user_id) ON DELETE CASCADE,
  lesson_id UUID NOT NULL REFERENCES public.lessons (lesson_id) ON DELETE CASCADE,
  score INTEGER NOT NULL CHECK (score BETWEEN 0 AND 100),
  answers JSONB NOT NULL DEFAULT '[]',
  completed_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX idx_quiz_attempts_user ON public.quiz_attempts (user_id, completed_at DESC);
