-- 1. USERS TABLOSU (Kullanıcı profilleri ve kredi dengesi)
CREATE TABLE public.users (
    user_id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    bio TEXT,
    role TEXT CHECK (role IN ('mentor', 'mentee', 'both')),
    credit_balance INTEGER DEFAULT 100 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. SKILLS TABLOSU (Kategori ve becerilerin master listesi)
CREATE TABLE public.skills (
    skill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name TEXT NOT NULL UNIQUE,
    category_name TEXT NOT NULL,
    type TEXT CHECK (type IN ('technical', 'academic', 'soft_skill')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. SESSIONS TABLOSU (Mentorluk seansları ve video linkleri)
CREATE TABLE public.sessions (
    session_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    mentor_id UUID REFERENCES public.users(user_id) ON DELETE RESTRICT NOT NULL,
    mentee_id UUID REFERENCES public.users(user_id) ON DELETE RESTRICT NOT NULL,
    -- (Görselde kesilen diğer sütunlar geliştirme sürecinde tamamlanacaktır)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
